grpc&kafka
igortoigildin/stupefied_bell pull request #3
Opened 2024-10-08 15:37 UTC by igortoigildin

2024-10-11 17:05 UTC, ValeryBMSTU requested changes
Хорошо, но я знаю, что ты можешь лучше

2024-10-11 17:05 UTC, ValeryBMSTU commented on internal/api/delgrpc/app/grpc/grpcapp.go
> +	port       int
Если есть порт, то должен быть и ip...

2024-10-11 17:05 UTC, ValeryBMSTU commented on cmd/client/main.go
> +	}
Не думаю, что подобный должен присутствовать в main.go

2024-10-11 17:05 UTC, ValeryBMSTU commented on cmd/client/main.go
> +	defer cancel()
Таймауты не должны быть жестко зашиты в исходный код. Должна быть возможность их настраивать через конфиг приложения

2024-10-11 17:05 UTC, ValeryBMSTU commented on Makefile
> +	proto/delivery_v1/delivery.proto
Красиво

2024-10-11 17:05 UTC, ValeryBMSTU commented on cmd/client/main.go
> +	"log"
Попробуй еще посмотреть в сторону пакета slog https://pkg.go.dev/log/slog

Он стильный, модный, молодежный

2024-10-11 17:05 UTC, ValeryBMSTU commented
![image](https://github.com/user-attachments/assets/d38a0c60-f908-4ae3-8e3a-2b7e679288a5)

2024-10-14 08:22 UTC, igortoigildin commented on bin/protoc-gen-go
Добавил .gitignore и убрал bin

2024-10-14 08:24 UTC, igortoigildin commented on cmd/client/main.go
> +	desc "github.com/igortoigildin/stupefied_bell/pkg/delivery_v1"
Переименовал в delivery

2024-10-14 09:02 UTC, igortoigildin commented on proto/delivery_v1/delivery.proto
> +    string status = 1; // Status to be set.
Добавил enum

2024-10-14 09:25 UTC, igortoigildin commented on cmd/client/main.go
> +
Обновил структуры cmd и internal соответственно

2024-10-14 09:51 UTC, igortoigildin commented on cmd/server/main.go
> +)
Вынес в config

2024-10-14 09:52 UTC, igortoigildin commented on internal/api/delgrpc/server.go
> +	}
Убрал.

2024-10-14 10:07 UTC, igortoigildin commented on migrations/000001_create_orders_table.up.sql
>  );
добавил enum

2024-10-14 16:35 UTC, igortoigildin commented on cmd/client/main.go
> +	}
Вынес в отдельную функцию в pkg

2024-10-14 16:35 UTC, igortoigildin commented on cmd/client/main.go
> +	defer cancel()
добавил config

2024-10-15 09:32 UTC, igortoigildin commented on cmd/client/main.go
> +	address         = "localhost:50051"
вынес в конфиг

2024-10-15 09:55 UTC, igortoigildin commented on pkg/lib/randOrder/order.go
> +		logger.Log.Error("failed to encode order for kafka", zap.Error(err))
поправил

2024-10-15 09:59 UTC, igortoigildin commented on proto/delivery_v1/delivery.proto
> +}
Обновил.

2024-10-15 10:04 UTC, igortoigildin commented on internal/storage/postgres/postgres.go
> +	UPDATE orders SET title = $1, quantity = $2, comment = $3, status = $4 WHERE number = $5;`
Изменил везде на id.

2024-10-15 10:05 UTC, igortoigildin commented on internal/api/delgrpc/server.go
> +	desc "github.com/igortoigildin/stupefied_bell/pkg/delivery_v1"
Убрал лишний.

2024-10-15 10:12 UTC, igortoigildin commented on internal/api/delgrpc/app/grpc/grpcapp.go
> +
Создал ошибку через errors.New и вернул в main

2024-10-15 10:25 UTC, igortoigildin commented on internal/api/delgrpc/app/grpc/grpcapp.go
> +	port       int
Добавил ip, но не совсем понятно почему сервер запускался только с одним портом..

2024-10-15 10:26 UTC, igortoigildin commented on cmd/client/main.go
> +	"log"
В сторону него давно смотрю, но как то привык к zap, и пока все в планах перейти на slog

2024-10-25 11:09 UTC, ValeryBMSTU commented on internal/api/delgrpc/app/grpc/grpcapp.go
> +	port       int
Очень многие библиотеки под капотом подставляют localhost

2024-10-25 11:50 UTC, ValeryBMSTU requested changes

2024-10-25 11:50 UTC, ValeryBMSTU commented on cmd/order/main.go
> +
Я думаю, что от подобного отладочного кода следует отказаться. Лучше это вынести в файлы  _test.go, т.е. использовать подходы и механизмы, которые предусмотрены языком, а не внедрять отладочные элементы непосредственно в кодовую базу приложения. 

Кстати, чтобы запустить все юнит-тесты сразу, можно использовать команду `go test ./...`

С другой стороны, есть небольшая проблема с тем, что кафка подразумевает межсервисное взаимодействие по сети, что делает тестирование в рамках юнит-тестов немного затруднительным. 

Возникает необходимость это либо как-то хитро замокать, либо где-нибудь написать клиент, который будет посылать запросы в уже поднятные сервисы и проверять, что они были обработаны и изменения в БД отобразились, т.е. проводить полноценное интеграционное 'натуралистичное' тестирование. Кстати, обычно этим занимаются Automation QA. Они не пишут юнит тесты, они пишут клиенты, которые шлют запросы в группу сервисов, при этом сами сервисы они для себя видят как черные ящики

2024-10-25 11:50 UTC, ValeryBMSTU commented on cmd/order/main.go
> +		IdleTimeout:  cfg.HTTPserver.IdleTimout,
Можно, кстати, это тоже засунуть в пакет api и сделать полный конструктор не только для роутера, но и для самого http сервера.

Вообще, в идеале, у тебя здесь в функции main дожлжны быть только вызовы конструкторов + ListenAndServe

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/api/rest/errors.go
> +}
В целом, единые форматы сообщении и какие-то полезные "чистые функции" (которые не зависят от предметной области, не обращаются к другим пакетам из internal и всегда возвращают один и тот же результат для одних и тех же аргументов) можно переместить в pkg, т.к. они  в равной степени могут быть использованы как для сервиса delivery, так и для сервиса order.

Я также попросил бы тебя удостовериться в том, что ни один из пакетов в директории internal/delivery/...   не импортирует какой-либо пакет из директории internal/order/... и наоборот

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/api/rest/handlerOrderNew.go
> +	"github.com/igortoigildin/stupefied_bell/pkg/logger"
Не имеет смысла создавать в /pkg директорию lib, т.к.  директорию pkg и так подразумевает, что они содержит какие-то пакеты-библиотеки, которые могут быть переиспользованы различными сервисами, в том числе и теми, которые находятся за пределеами данного репозитория

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/api/rest/handlerUpdateStatus.go
> +
Почему  Response ?

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/api/rest/router.go
> +}
Я бы рекомендовал функции-handler`ы привязать к какой-нибудь структуре в виде её методов, и в эту же структуру зашить парметры cfg, к которым ты сможешь обращаться из хенделров при необходимости + ты сможешь таким образом избежать констуркции, когда ты из функции возвращаешь фукнцию, которая замыкается на переданный cfg:

`func handlerUpdateStatus(cfg *config.Config) echo.HandlerFunc {
	return func(c echo.Context) error {``

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/app/app.go
> +
an empty line at the beginning of the function

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/services/grpcResp.go
> +	"github.com/igortoigildin/stupefied_bell/pkg/logger"
Пока что нет смысла в версионировании v1 и т.п. Кроме того, это делается немного по другому. Обычно создается отдельный подпакет, т.е. .../delivery/v1

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/delivery/services/grpcResp.go
> +func SendGRPCResponse(cfg *config.Config, status string, id string) error {
Response?

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/order/api/grpc/app/grpc/grpcapp.go
> +	ip 			net.IP
Кажется, что форматирование поехало. Нужно либо поднастроить VS code, либо прожимать команду `go fmt ./...` в корне проекта

2024-10-25 11:50 UTC, ValeryBMSTU commented on internal/order/api/grpc/server.go
> +	storage "github.com/igortoigildin/stupefied_bell/internal/order/storage"
Не совсем понятно почему api --> repo и storage --> storage

2024-10-27 10:45 UTC, igortoigildin commented on internal/delivery/api/rest/handlerOrderNew.go
> +	"github.com/igortoigildin/stupefied_bell/pkg/logger"
перенес все в pkg, убрал lib

2024-10-27 11:36 UTC, igortoigildin commented on internal/delivery/api/rest/router.go
> +}
Добавил структуру OrderController и переписал хендлеры в виде методов к ней.

2024-10-27 11:37 UTC, igortoigildin commented on internal/delivery/app/app.go
> +
убрал

2024-10-27 11:43 UTC, igortoigildin commented on internal/delivery/services/grpcResp.go
> +func SendGRPCResponse(cfg *config.Config, status string, id string) error {
исправил на request

2024-10-27 11:43 UTC, igortoigildin commented on internal/delivery/services/grpcResp.go
> +	"github.com/igortoigildin/stupefied_bell/pkg/logger"
убрал версию

2024-10-27 11:56 UTC, igortoigildin commented on internal/delivery/api/rest/handlerUpdateStatus.go
> +
Изменил на request

2024-10-27 12:18 UTC, igortoigildin commented on internal/delivery/api/rest/errors.go
> +}
Перенес в pkg. Так же проверил на импорты между пакетами internal/delivery/... и internal/order/...

2024-10-27 12:31 UTC, igortoigildin commented on cmd/order/main.go
> +		IdleTimeout:  cfg.HTTPserver.IdleTimout,
Добавил один общий конструктор для сервера, роутера и storage.

2024-10-27 13:15 UTC, igortoigildin commented on cmd/order/main.go
> +
убрал отладочный код, интерграционные тесты пока не реализовывал, тк пока не до конца понятно реализация непосредственной кафки в кодовой базы, но отметил себе этот вопрос чтобы не забыть

2024-10-27 13:18 UTC, igortoigildin commented on internal/order/api/grpc/app/grpc/grpcapp.go
> +	ip 			net.IP
прогнал go fmt ./...

2024-10-27 13:33 UTC, igortoigildin commented on internal/order/api/grpc/server.go
> +	storage "github.com/igortoigildin/stupefied_bell/internal/order/storage"
обновил repo на storage

2024-11-19 15:19 UTC, merged